package ClientStub;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DlmsService", targetNamespace = "http://Server/", wsdlLocation = "file:/C:/Users/alekh/eclipse-workspace/DLMS_WS/bin/DlmsService.wsdl")
public class DlmsService
    extends Service
{

    private final static URL DLMSSERVICE_WSDL_LOCATION;
    private final static WebServiceException DLMSSERVICE_EXCEPTION;
    private final static QName DLMSSERVICE_QNAME = new QName("http://Server/", "DlmsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/alekh/eclipse-workspace/DLMS_WS/bin/DlmsService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DLMSSERVICE_WSDL_LOCATION = url;
        DLMSSERVICE_EXCEPTION = e;
    }

    public DlmsService() {
        super(__getWsdlLocation(), DLMSSERVICE_QNAME);
    }

    public DlmsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DLMSSERVICE_QNAME, features);
    }

    public DlmsService(URL wsdlLocation) {
        super(wsdlLocation, DLMSSERVICE_QNAME);
    }

    public DlmsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DLMSSERVICE_QNAME, features);
    }

    public DlmsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DlmsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IServerInterface
     */
    @WebEndpoint(name = "DlmsPort")
    public IServerInterface getDlmsPort() {
        return super.getPort(new QName("http://Server/", "DlmsPort"), IServerInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IServerInterface
     */
    @WebEndpoint(name = "DlmsPort")
    public IServerInterface getDlmsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Server/", "DlmsPort"), IServerInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DLMSSERVICE_EXCEPTION!= null) {
            throw DLMSSERVICE_EXCEPTION;
        }
        return DLMSSERVICE_WSDL_LOCATION;
    }

}
